version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/development/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/www:/usr/share/nginx/www
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '8080:80'
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: 'sapl'
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - '16379:6379'
  fuseki:
    image: stain/jena-fuseki
    ports:
      - '3030:3030'
