version: '3'
services:
  webapp:
    build: ./web
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: 'sapl'
  redis:
    image: redis
